/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function createAutomaton(patterns: Array<string>, matchKind?: number | undefined | null): Automaton
export const MATCH_KIND_STANDARD: number
export const MATCH_KIND_LEFTMOST_LONGEST: number
export const MATCH_KIND_LEFTMOST_FIRST: number
export declare class Automaton {
  constructor(patterns: Array<string>, matchKind?: number | undefined | null)
  find(haystack: string): Array<string>
}
